# Generated by Django 6.0.7 on 2026-07-18 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(blank=True, max_length=150, verbose_name='Nombre comercial')),
                ('razon_social', models.CharField(blank=True, max_length=150, verbose_name='Razón social')),
                ('nit', models.CharField(blank=True, max_length=30, verbose_name='NIT')),
                ('tipo_empresa', models.CharField(blank=True, choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], max_length=20, verbose_name='Tipo de empresa')),
                ('regimen_tributario', models.CharField(blank=True, choices=[('simplificado', 'Régimen Simplificado'), ('comun', 'Régimen Común'), ('simple', 'Régimen Simple de Tributación'), ('no_responsable', 'No Responsable de IVA')], max_length=20, verbose_name='Régimen tributario')),
                ('responsable_iva', models.BooleanField(default=True, verbose_name='Responsable de IVA')),
                ('actividad_economica', models.CharField(blank=True, help_text='Código CIIU y/o descripción de la actividad principal.', max_length=150, verbose_name='Actividad económica')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('pais', models.CharField(blank=True, default='Colombia', max_length=100, verbose_name='País')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio / Ciudad')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web')),
                ('moneda', models.CharField(choices=[('COP', 'Peso Colombiano (COP)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('MXN', 'Peso Mexicano (MXN)')], default='COP', max_length=3, verbose_name='Moneda')),
                ('simbolo_moneda', models.CharField(default='$', max_length=5, verbose_name='Símbolo de moneda')),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=5, verbose_name='Idioma')),
                ('zona_horaria', models.CharField(default='America/Bogota', max_length=50, verbose_name='Zona horaria')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('suspendida', 'Suspendida'), ('prueba', 'En prueba')], default='activa', max_length=20, verbose_name='Estado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('licencia', models.CharField(blank=True, default='Estándar', max_length=50, verbose_name='Licencia')),
                ('version_erp', models.CharField(blank=True, default='1.0', max_length=20, verbose_name='Versión del ERP')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_principal', models.ImageField(blank=True, help_text='Usado en el dashboard, PDF y correo electrónico.', null=True, upload_to='empresa/logos/', verbose_name='Logo principal')),
                ('logo_impresion', models.ImageField(blank=True, help_text='Versión optimizada (monocromática) para impresión térmica.', null=True, upload_to='empresa/logos/', verbose_name='Logo para impresión')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='empresa/favicon/', verbose_name='Favicon')),
                ('color_primario', models.CharField(default='#2563eb', max_length=7, verbose_name='Color primario')),
                ('color_secundario', models.CharField(default='#9333ea', max_length=7, verbose_name='Color secundario')),
                ('color_botones', models.CharField(default='#2563eb', max_length=7, verbose_name='Color de botones')),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro'), ('auto', 'Automático')], default='claro', max_length=10, verbose_name='Tema')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identidad_visual', to='company.company')),
            ],
            options={
                'verbose_name': 'Identidad Visual',
                'verbose_name_plural': 'Identidad Visual',
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_remitente', models.CharField(blank=True, max_length=150, verbose_name='Nombre remitente')),
                ('correo_remitente', models.EmailField(blank=True, max_length=254, verbose_name='Correo remitente')),
                ('firma', models.TextField(blank=True, verbose_name='Firma')),
                ('plantilla_html', models.TextField(blank=True, help_text='Plantilla base reutilizable para los correos enviados por el sistema.', verbose_name='Plantilla HTML')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correo_config', to='company.company')),
            ],
            options={
                'verbose_name': 'Configuración de Correo',
                'verbose_name_plural': 'Configuración de Correo',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo_facturacion', models.CharField(blank=True, max_length=10, verbose_name='Prefijo de facturación')),
                ('consecutivo_inicial', models.PositiveIntegerField(default=1, verbose_name='Consecutivo inicial')),
                ('consecutivo_actual', models.PositiveIntegerField(default=1, verbose_name='Consecutivo actual')),
                ('resolucion_dian', models.CharField(blank=True, max_length=50, verbose_name='Resolución DIAN')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('fecha_vencimiento_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento de la resolución')),
                ('tipo_documento', models.CharField(choices=[('factura_venta', 'Factura de Venta'), ('pos', 'Documento POS'), ('nota_credito', 'Nota Crédito'), ('nota_debito', 'Nota Débito')], default='factura_venta', max_length=20, verbose_name='Tipo de documento')),
                ('nota_legal', models.TextField(blank=True, verbose_name='Nota legal')),
                ('politica_devolucion', models.TextField(blank=True, verbose_name='Política de devolución')),
                ('mensaje_agradecimiento', models.CharField(blank=True, max_length=255, verbose_name='Mensaje de agradecimiento')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facturacion', to='company.company')),
            ],
            options={
                'verbose_name': 'Configuración de Facturación',
                'verbose_name_plural': 'Configuración de Facturación',
            },
        ),
        migrations.CreateModel(
            name='PrintSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano_ticket', models.CharField(choices=[('58mm', '58 mm'), ('80mm', '80 mm'), ('carta', 'Carta')], default='80mm', max_length=10, verbose_name='Tamaño de ticket')),
                ('margenes', models.CharField(default='5,5,5,5', help_text='Formato: superior,inferior,izquierdo,derecho', max_length=50, verbose_name='Márgenes (mm)')),
                ('mostrar_logo', models.BooleanField(default=True, verbose_name='Mostrar logo')),
                ('mostrar_qr', models.BooleanField(default=False, verbose_name='Mostrar QR')),
                ('mostrar_codigo_barras', models.BooleanField(default=False, verbose_name='Mostrar código de barras')),
                ('copias_defecto', models.PositiveSmallIntegerField(default=1, verbose_name='Copias por defecto')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impresion', to='company.company')),
            ],
            options={
                'verbose_name': 'Configuración de Impresión',
                'verbose_name_plural': 'Configuración de Impresión',
            },
        ),
        migrations.CreateModel(
            name='SalesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitir_venta_sin_stock', models.BooleanField(default=False, verbose_name='Permitir vender sin stock')),
                ('aplicar_iva_defecto', models.BooleanField(default=True, verbose_name='Aplicar IVA por defecto')),
                ('iva_defecto_porcentaje', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='IVA por defecto (%)')),
                ('redondear_precios', models.BooleanField(default=False, verbose_name='Redondear precios')),
                ('mostrar_imagen_producto', models.BooleanField(default=True, verbose_name='Mostrar imagen del producto')),
                ('mostrar_codigo_barras', models.BooleanField(default=True, verbose_name='Mostrar código de barras')),
                ('mostrar_descuento', models.BooleanField(default=True, verbose_name='Mostrar descuento')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_config', to='company.company')),
            ],
            options={
                'verbose_name': 'Configuración de Ventas',
                'verbose_name_plural': 'Configuración de Ventas',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_principal', models.CharField(blank=True, max_length=30, verbose_name='Número principal')),
                ('mensaje_venta', models.TextField(blank=True, default='Hola {cliente}, gracias por tu compra #{numero}. Total: {total}.', verbose_name='Mensaje automático de venta')),
                ('mensaje_reparacion', models.TextField(blank=True, default='Hola {cliente}, tu equipo (orden {numero}) ha cambiado de estado: {estado}.', verbose_name='Mensaje automático de reparación')),
                ('mensaje_garantia', models.TextField(blank=True, default='Hola {cliente}, tu garantía para el producto {producto} vence el {fecha_vencimiento}.', verbose_name='Mensaje automático de garantía')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='company.company')),
            ],
            options={
                'verbose_name': 'Configuración de WhatsApp',
                'verbose_name_plural': 'Configuración de WhatsApp',
            },
        ),
    ]
