# Generated by Django 6.0.7 on 2026-07-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='condiciones_servicio_tecnico',
            field=models.TextField(blank=True, default='Garantía de 30 días calendario sobre el repuesto instalado. No cubre daños por mal uso, humedad o intervención de terceros.', help_text='Texto que se muestra en el pie del recibo de servicio técnico.', verbose_name='Condiciones de garantía (Servicio Técnico)'),
        ),
    ]
