# Generated by Django 6.0.7 on 2026-07-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.PositiveIntegerField(blank=True, help_text='Consecutivo de facturación asignado de forma atómica al confirmar la venta (ver Sale.asignar_numero_factura). Nulo en ventas antiguas creadas antes de activar la numeración; nunca se reutiliza ni se genera retroactivamente.', null=True, unique=True, verbose_name='Número de factura'),
        ),
    ]
